### ISSUE TITLE
Running d4 in  OSX ? 

### ISSUE THREAD

**Issue by CountingLogic** [crillab/d4#2]
Hi, when I try to run the following commands, as recommended on Github repo : 
cd core
make -j8

I get the following error:
make: *** No targets specified and no makefile found.  Stop.

But, running the make command in "d4-main" gives me the following output:

Compiling: objs/Main.o
Compiling: objs/MinCutPartitioner.o
Compiling: objs/VariableHeuristicInterface.o
Compiling: objs/ParserProblem.o
Compiling: objs/dynamicOccurrenceManager.o
Compiling: objs/Preproc.o
Compiling: objs/Communicator.o
Compiling: objs/Solver.o
In file included from utils/Communicator.cc:19:
utils/Communicator.hh:27:10: fatal error: 'boost/multiprecision/gmp.hpp' file not found
#include <boost/multiprecision/gmp.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [objs/Communicator.o] Error 1
make: *** Waiting for unfinished jobs....
preproc/Preproc.cc:20:10: fatal error: 'boost/tokenizer.hpp' file not found
#include <boost/tokenizer.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
heuristics/MinCutPartitioner.cc:21:10: fatal error: 'boost/graph/adjacency_list.hpp' file not found
#include <boost/graph/adjacency_list.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from utils/Solver.cc:48:
utils/../DAG/DAG.hh:21:10: fatal error: 'gmpxx.h' file not found
#include <gmpxx.h>
         ^~~~~~~~~
1 error generated.
1 error generated.
make: *** [objs/Preproc.o] Error 1
make: *** [objs/MinCutPartitioner.o] Error 1
In file included from manager/dynamicOccurrenceManager.cc:19:
In file included from manager/../manager/dynamicOccurrenceManager.hh:28:
manager/../DAG/DAG.hh:21:10: fatal error: 'gmpxx.h' file not found
#include <gmpxx.h>
         ^~~~~~~~~
In file included from manager/ParserProblem.cc:29:
manager/../DAG/DAG.hh:21:10: fatal error: 'gmpxx.h' file not found
#include <gmpxx.h>
         ^~~~~~~~~
In file included from interfaces/VariableHeuristicInterface.cc:30:
interfaces/../DAG/DAG.hh:21:10: fatal error: 'gmpxx.h' file not found
#include <gmpxx.h>
         ^~~~~~~~~
In file included from core/Main.cc:26:
In file included from core/../modelCounters/ModelCounter.hh:34:
In file included from core/../modelCounters/../manager/dynamicOccurrenceManager.hh:28:
core/../manager/../DAG/DAG.hh:21:10: fatal error: 'gmpxx.h' file not found
#include <gmpxx.h>
         ^~~~~~~~~
1 error generated.
1 error generated.
make: *** [objs/Solver.o] Error 1
make: *** [objs/VariableHeuristicInterface.o] Error 1
1 error generated.
make: *** [objs/ParserProblem.o] Error 1
1 error generated.
make: *** [objs/dynamicOccurrenceManager.o] Error 1
1 error generated.
make: *** [objs/Main.o] Error 1

I have tried many things : adding path of boost libraries through the -I flag, and adding gmpxx.h directly to the folder, but nothing seems to work.  Any help would be much appreciated

**Comment by jm62300** [comment]
I will have a look, please assign the issue to me ... otherwise I do not receive an email.

**Comment by jm62300** [comment]
I cannot test because I do not use OSX.
Did you install the libgmp?

**Comment by CountingLogic** [comment]
Hey thanks for the reply, I am still getting the same error and I already had libgmp

**Comment by jm62300** [comment]
I just test on my mac and I also have the same issue.
I will try to compile it on my laptop, I keep you poster.

**Comment by jm62300** [comment]
Actually I did not success in compiling the software because my mac is almost dead :D 
Can you test by adding -L pathToBoostLib ?

**Comment by jm62300** [comment]
I success in compiling d4 on my MAC.
To do it I added the path to boost/lib using -L.
And, most important I replace clang++ by g++.
I am not sure, but it looks like clang does not really like boost (or my knowledge about MAC OS are not good enough).

**Comment by jm62300** [comment]
Actually for projection you cannot use decomposition heuristic.
Please test with the option -pv=NO.
